site_name: ACCESS-Hive

# Needed to generate the canonical_url for each pages that are 
# then used to create the sitemap for search engine indexing
site_url: https://access-hive.org.au
# Git repository
repo_url: https://github.com/ACCESS-Hive/access-hive.github.io
repo_name: ACCESS-Hive
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode


  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.expand
    # - navigation.path
    # - toc.integrate
    # - navigation.sections
    - content.code.copy        # for displaying copy icon at top right in code snippets  
    - content.code.annotate

  logo: assets/ACCESS_icon_HIVE.png
  favicon: assets/ACCESS_icon_HIVE.png
  icon:
    edit: material/pencil
    view: material/eye
copyright: Copyright &copy; 2022 ACCESS-NRI

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search
  - macros
  - bibtex:
      bib_file: "references.bib"
  - events:
      events_dir: events/events

# Extensions
markdown_extensions: 
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - footnotes
  - tables
  - pymdownx.keys

# Navigation
nav:
  - Home: 
    - index.md
    - home/features.md
    - home/community.md

  - Models: 
    - Models: models/index.md
    - Model Components: 
      - Overview: models/model-components.md
      - Atmosphere: models/model_components/atmosphere.md
      - Land: models/model_components/land.md
      - Ocean: models/model_components/ocean.md
      - Sea Ice: models/model_components/sea-ice.md
      - Aerosols and Atmospheric Chemistry: models/model_components/aerosols_atmospheric_chemistry.md
      - Biogeochemistry Land: models/model_components/bgc_land.md
      - Biogeochemistry Ocean: models/model_components/bgc_ocean.md
      - Coupler: models/model_components/coupler.md

    - Model Configurations: 
      - Overview: models/model-configurations.md
      - ACCESS-ESM: models/configurations/access-esm.md
      - ACCESS-CM: models/configurations/access-cm.md
      - ACCESS-AM: models/configurations/access-am.md
      - ACCESS-OM: models/configurations/access-om.md
      - ACCESS-S: models/configurations/access-s.md

    - Running a Model: 
      - Overview: models/running-a-model.md
      - Run ACCESS-ESM: models/running-a-model/running-access-esm.md
      - Run ACCESS-CM: models/running-a-model/running-access-cm.md
      - Run ACCESS-AM: models/running-a-model/running-access-am.md
      - Run ACCESS-OM2: models/running-a-model/running-access-om.md
      - Run ACCESS-S: models/running-a-model/running-access-s.md

    - Model Evaluation and Data: 
      - Overview: models/model-evaluation-and-data.md
      - Atmosphere: models/model_evaluation/atmosphere.md
      - Land: models/model_evaluation/land.md
      - Ocean Sea-ice: models/model_evaluation/ocean_seaice.md
      - Biogeochemistry Ocean: models/model_evaluation/bgc_ocean.md
      - Diagnostics: models/model_evaluation/diagnostics.md
      - Data processing: models/model_evaluation/data_processing.md
      - Data catalogs: models/model_evaluation/data_catalogs.md

  - Training: 
    - Training: training/index.md
    - Git Version Control: training/git-version-control.md
    - High Performance Computing (HPC): training/hpc.md
    - ACCESS Training: training/ACCESS_training.md
    - NCI Training: training/nci-training.md
    - Additional Training: training/additional_training.md

  - Resources:
    # - Resources: resources/index.md
    - Working Groups: resources/working-groups.md
    - ACCESS-HIVE Forum: resources/access-hive-forum.md
    - Data: resources/data.md
    - Glossary: resources/glossary.md
    - Policies: resources/policies.md
    - Events: 
      - Overview: resources/events/index.md
      - Add Event: resources/events/add_event.md

  - Contribute: 
    - Contribute: contribute/index.md
    - Edit on Github: contribute/edit-on-github.md
    - Edit Locally: contribute/edit-locally.md
    - Stand-alone Documentation: contribute/standalone-documentation.md
    - Change the Navigation: contribute/change-the-navigation.md
    - Reviewers: contribute/reviewers.md

  - About:
    # - About: about/index.md
    - Contact: about/contact.md
    - Support: about/support.md
    - Code of Conduct: about/code_of_conduct.md
    - License: about/License.md

# Footer
extra:
  generator: false
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel
  analytics:
    provider: google
    property: G-2T6SQEH2CX
  supported: '<a href="https://access-hive.org.au/about/support"><i class="icon-supported" title="Supported by ACCESS-NRI"></i></a>'
  recommended: '<a href="https://access-hive.org.au/about/support"><i class="icon-recommended" title="Recommended by ACCESS-NRI"></i></a>'
  community: '<a href="https://access-hive.org.au/about/support"><i class="icon-community" title="Community Contributed"></i></a>'

extra_css:
  - css/termynal.css
  - css/custom.css
  - css/access-nri.css
  - css/fontello.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js