site_name: ACCESS-Hub

# Git repository
repo_url: https://github.com/ACCESS-Hub/ACCESS-Hub
repo_name: ACCESS-Hub
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - scheme: light
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  logo: assets/ACCESSLogoJustPlanet.png

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: index.md
  - ACCESS-NRI: ACCESS-NRI/ACCESS-NRI.md
  - Community: 
    - Generate Bathymetry: Community/Bathymetry.md
  - How to contribute: 
    - How to contribute: Help/How_to_contribute.md
    - Setup: Help/contribution_setup.md
    - Modify the documentation: Help/modify_documentation.md
    - Change the navigation: Help/change_navigation.md