site_name: ACCESS-Hub - Community

# Git repository
repo_url: https://github.com/ACCESS-Hub/ACCESS-Hub
repo_name: ACCESS-Hub
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  palette:
    - scheme: light
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  logo: assets/ACCESSLogoJustPlanet.png

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Modelling:
    - Ocean/Sea-Ice: Community/modelling/ocean_seaice/missing.md
    - ACCESS Coupled: Community/modelling/access_coupled/missing.md
    - ACCESS Seasonal: Community/modelling/access_seasonal/missing.md
    - Land: Community/modelling/land/missing.md
    - Regional Atmosphere: Community/modelling/regional_atmosphere/missing.md
    - Regional Ocean: Community/modelling/regional_ocean/missing.md
    - Biogeochemistry: Community/modelling/biogeochemistry/missing.md
  - Evaluation and Analysis:
    - CMIP: 
      - CMIP6:
        - Sublevel 1: Community/evaluation_and_analysis/CMIP/CMIP6/missing.md
        - Sublevel 2: Community/evaluation_and_analysis/CMIP/CMIP6/missing.md
      - CMIP5: Community/evaluation_and_analysis/CMIP/CMIP5/missing.md
    - Land: Community/evaluation_and_analysis/land/missing.md
    - Ocean Sea-ice: Community/evaluation_and_analysis/ocean_seaice/missing.md
    - Atmosphere: Community/evaluation_and_analysis/atmosphere/missing.md
    - Machine Learning: Community/evaluation_and_analysis/machine_learning/missing.md
    - General: Community/evaluation_and_analysis/general/missing.md
  - Training resources:
    - General technical: Community/training/general_technical/missing.md
    - Modelling: Community/training/modelling/missing.md
    - Analysis: Community/training/analysis/missing.md
  - How to contribute: 
    - How to contribute: Help/How_to_contribute.md
    - Setup: Help/contribution_setup.md
    - Modify the documentation: Help/modify_documentation.md
    - Change the navigation: Help/change_navigation.md
  - ACCESS-NRI: ACCESS-NRI/index.html
