site_name: ACCESS-Hive

# Needed to generate the canonical_url for each pages that are 
# then used to create the sitemap for search engine indexing
site_url: https://access-hive.org.au
# Git repository
repo_url: https://github.com/ACCESS-Hive/access-hive.github.io
repo_name: ACCESS-Hive
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    # - scheme: light
    #   primary: indigo
    #   accent: deep orange
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      # toggle:
      #   icon: material/weather-night
      #   name: Switch to light mode


  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - search.share
    # - navigation.expand
    # - navigation.path
    # - toc.integrate
    # - navigation.sections
    - content.code.copy        # for displaying copy icon at top right in code snippets  
    - content.code.annotate

  logo: assets/ACCESS_icon_HIVE.png
  favicon: assets/ACCESS_icon_HIVE.png
  icon:
    edit: material/pencil
    view: material/eye
copyright: Copyright &copy; 2022 ACCESS-NRI

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search
  - macros
  - bibtex:
      bib_file: "references.bib"
  - events:
      events_dir: community_resources/events/events

# Extensions
markdown_extensions: 
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - def_list
  - footnotes
  - tables
  - pymdownx.keys

# Navigation
nav:
  - Home: 
    - index.md
    - Contact: about/contact.md
    - Support: about/support.md
    - Code of conduct: about/code_of_conduct.md
    - Policies: about/policies.md
    - License: about/License.md

  - Models: 
    - Models: models/index.md
    - Model Components: 
      - Overview: models/model_components/index.md
      - Atmosphere: models/model_components/atmosphere.md
      - Land: models/model_components/land.md
      - Ocean: models/model_components/ocean.md
      - Sea Ice: models/model_components/sea-ice.md
      - Aerosols and Atmospheric Chemistry: models/model_components/aerosols_atmospheric_chemistry.md
      - Biogeochemistry Land: models/model_components/bgc_land.md
      - Biogeochemistry Ocean: models/model_components/bgc_ocean.md
      - Coupler: models/model_components/coupler.md

    - Model Configurations: 
      - Overview: models/configurations/index.md
      - ACCESS-ESM: models/configurations/access-esm.md
      - ACCESS-CM: models/configurations/access-cm.md
      - ACCESS-AM: models/configurations/access-am.md
      - ACCESS-OM: models/configurations/access-om.md

  - Run a Model: 
    - models/running-a-model/index.md
    # If we add an additional subsection
    # - Getting Started: 
    #   - models/running-a-model/getting_started/index.md
    #   - Access to Gadi@NCI: models/running-a-model/getting_started/access_to_gadi_at_nci.md
    - Access to Gadi@NCI: models/running-a-model/getting_started/access_to_gadi_at_nci.md
    - Run ACCESS-ESM: models/running-a-model/running-access-esm.md
    - Run ACCESS-CM: models/running-a-model/running-access-cm.md
    - Run ACCESS-AM: models/running-a-model/running-access-am.md
    - Run ACCESS-OM: models/running-a-model/running-access-om.md

  - Model Evaluation:
    - model_evaluation/index.md
    - Getting Started: 
      - model_evaluation/model_evaluation_getting_started/index.md
      - Access to Gadi@NCI: model_evaluation/model_evaluation_getting_started/access_to_gadi_at_nci.md
      - Model Evaluation on Gadi: model_evaluation/model_evaluation_getting_started/model_evaluation_getting_started.md
    - Observational Data Catalog: model_evaluation/model_evaluation_observational_catalogs.md
    - Model Data Catalog:
      - model_evaluation/model_evaluation_model_catalogs/index.md
      - Search Model Catalog: model_evaluation/model_evaluation_model_catalogs/model_evaluation_search_models.md
      - Add your Model to the Catalog: model_evaluation/model_evaluation_model_catalogs/model_evaluation_add_models.md
    - Data Format Processing: model_evaluation/model_evaluation_data_processing.md
    - Model Evaluation on Gadi: 
      - model_evaluation/model_evaluation_on_gadi/index.md
      - ilamb: model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_ilamb.md
      - esmvalltool: model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool.md
    - Evaluation Recipe Gallery: model_evaluation/model_evaluation_recipe_gallery.md

  - Community Resources:
    - community_resources/index.md
    - Community Working Groups: community_resources/community_working_groups.md
    - Community Glossaries:
      - community_resources/glossaries/index.md
      - ACCESS-NRI: community_resources/glossaries/glossary_access_nri.md
      - IPCC: community_resources/glossaries/glossary_ipcc.md
      - CSSR: community_resources/glossaries/glossary_cssr.md
      - CMIP(6): community_resources/glossaries/glossary_cmip.md
      - ERA(5): community_resources/glossaries/glossary_era.md
      - UM: community_resources/glossaries/glossary_um.md
    - Community Training: 
      - Training: community_resources/training/index.md
      - Git Version Control: community_resources/training/git-version-control.md
      - High Performance Computing (HPC): community_resources/training/hpc.md
      - ACCESS Training: community_resources/training/ACCESS_training.md
      - NCI Training: community_resources/training/nci-training.md
      - Additional Training: community_resources/training/additional_training.md
    - Community Events:
       - community_resources/events/index.md
       - Add Event: community_resources/events/add_event.md
    - Community Observational Catalogs: community_resources/community_observational_catalogs.md
    - Community Model Catalogs: community_resources/community_model_catalogs.md
    - Community Data Formatting: community_resources/community_data_processing.md
    - Community Model Evaluation Recipes: community_resources/community_med_recipes.md
    - Contribute: 
      - Contribute: contribute/index.md
      - Edit on Github: contribute/edit-on-github.md
      - Edit Locally: contribute/edit-locally.md
      - Stand-alone Documentation: contribute/standalone-documentation.md
      - Change the Navigation: contribute/change-the-navigation.md
      - Reviewers: contribute/reviewers.md

  - Community Forum: https://forum.access-hive.org.au
  # - [Community Forum](https://forum.access-hive.org.au){ .md_button }

# Footer
extra:
  generator: false
  # version:
  #   provider: mike
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel
  analytics:
    provider: google
    property: G-2T6SQEH2CX

  # Original implementation
  # supported: '<a href="https://access-hive.org.au/about/support"><i class="icon-supported" title="Supported by ACCESS-NRI"></i></a>'
  # recommended: '<a href="https://access-hive.org.au/about/support"><i class="icon-recommended" title="Recommended by ACCESS-NRI"></i></a>'
  # community: '<a href="https://access-hive.org.au/about/support"><i class="icon-community" title="Community Contributed"></i></a>'

  # Octicons experimental 
  # supported: ':octicons-check-circle-24:{ .icon-supported title="Supported by ACCESS-NRI" }'
  # recommended: ':octicons-star-24:{ .icon-recommended title="Recommended by ACCESS-NRI" }'
  # community: ':octicons-heart-fill-24:{ .heart title="Community contributed" }'

  # Material icons experimental
  # supported: '<a href="https://access-hive.org.au/about/support"><i class="material-icons icon-supported" title="Supported by ACCESS-NRI">check_circle_outlined</i></a>'
  # recommended: '<a href="https://access-hive.org.au/about/support"><i class="material-icons icon-recommended" title="Recommended by ACCESS-NRI">star</i></a>'
  # community: '<a href="https://access-hive.org.au/about/support"><i class="material-icons heart" title="Community Contributed">favorite</i></a>'

  # Fontawesome icons
  supported: '<a href="https://access-hive.org.au/about/support"><span class="icon-supported center-icons"><i class="fa fa-check" title="Supported by ACCESS-NRI"></i></span></a>'
  recommended: '<a href="https://access-hive.org.au/about/support"><span class="icon-recommended center-icons"><i class="fa fa-star" title="Recommended by ACCESS-NRI"></i></span></a>'
  community: '<a href="https://access-hive.org.au/about/support"><span class="heart center-icons"><i class="heart fa fa-heart" title="Community Contributed"></i></span></a>'

extra_css:
  - css/termynal.css
  - css/custom.css
  - css/access-nri.css
  - css/fontello.css
  - "https://fonts.googleapis.com/icon?family=Material+Icons"   # Material Icons Reference - https://material.io/resources/icons/?style=baseline
  - css/fontawesome-free-6.4.0-web/css/fontawesome.css
  - css/fontawesome-free-6.4.0-web/css/solid.css

extra_javascript:
  - js/termynal.js
  - js/custom.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js     # For tablesort functionality 
  - js/tablesort.js
