site_name: ACCESS-Hub

# Git repository
repo_url: https://github.com/ACCESS-Hub/ACCESS-Hub
repo_name: ACCESS-Hub
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  palette:
    - scheme: light
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  logo: assets/ACCESSLogoJustPlanet.png

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: index.md
  - ACCESS-NRI: 
    - Releases:
      - ACCESS-OM
      - ACCESS-AM
      - ACCESS-ESM
      - ACCESS-CM
    - Model Components:
        - Land
        - Ocean
        - Ice
        - Atmosphere
        - Coupler
    - Documentation and Training:
        - Technical
        - Analysis
        - Data
        - Policies : ACCESS-NRI/policies.md
    - Model Evaluation:
        - Tools
        - Tutorials
        - Background information
    - Working Groups:
        - Ocean-Sea Ice (COSIMA)
        - Atmosphere
        - Coupled Models
        - Land
        - Technical
        - Next Generation Methods
  - Community: 
    - Modelling:
      - Ocean/Sea-Ice
      - ACCESS Coupled
      - ACCESS Seasonal
      - Land
      - Regional Atmosphere
      - Regional Ocean
      - Biogeochemistry
    - Evaluation and Analysis:
      - CMIP
      - Land
      - Ocean Sea-ice
      - Atmosphere
      - Machine Learning
      - General
    - Training resources:
      - General technical
      - Modelling
      - Analysis
  - How to contribute: 
    - How to contribute: Help/How_to_contribute.md
    - Setup: Help/contribution_setup.md
    - Modify the documentation: Help/modify_documentation.md
    - Change the navigation: Help/change_navigation.md