site_name: ACCESS Hive

# Git repository
repo_url: https://github.com/ACCESS-Hub/ACCESS-Hub
repo_name: ACCESS-Hub
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

  logo: assets/ACCESSLogoJustPlanet.png
  favicon: assets/ACCESSLogoJustPlanet.png

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search
  - macros

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - ACCESS Hive:
    - index.md
  - Configurations: 
    - configurations/index.md
    - ACCESS-ESM: configurations/access-esm.md
    - ACCESS-CM: configurations/access-cm.md
    - ACCESS-AM: configurations/access-am.md
    - ACCESS-OM: configurations/access-om.md
  - Model Components: 
    - model_components/index.md
    - Atmosphere: model_components/atmosphere.md
    - Land: model_components/land.md
    - Ocean: model_components/ocean.md
    - Sea Ice: model_components/sea-ice.md
    - Aerosols and Atmospheric Chemistry: model_components/aerosols_atmospheric_chemistry.md
    - Biogeochemistry Land: model_components/bgc_land.md
    - Biogeochemistry Ocean: model_components/bgc_ocean.md
    - Coupler: model_components/coupler.md
  - Model Evaluation & Data: 
    - model_evaluation/index.md
    - Atmosphere: model_evaluation/atmosphere.md
    - Land: model_evaluation/land.md
    - Ocean Sea-ice: model_evaluation/ocean_seaice.md
    - Data processing: model_evaluation/data_processing.md
    - Data catalogs: model_evaluation/data_catalogs.md
  - Documentation and Training: 
    - docs_and_training/index.md
    - Policies : docs_and_training/policies.md
    - Technical: docs_and_training/technical.md
  - Working Groups:
    - Ocean-Sea Ice (COSIMA): working_groups/ocean_seaice.md
    - Atmosphere: working_groups/atmosphere.md
    - Coupled Models: working_groups/coupled.md
    - Land: working_groups/land.md
    - Technical: working_groups/technical.md
    - Next Generation Methods: working_groups/ngms.md
  - Events: 
    - events/index.md
    - Conferences: events/conferences.md
    - Workshops: events/workshops.md
  - About:
    - about/index.md

# Footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel
  analytics:
    provider: google
    property: G-2T6SQEH2CX
  supp: '<i class="icon-supported" title="Supported by ACCESS-NRI"></i>'
  recom: '<i class="icon-recommended" title="Recommended by ACCESS-NRI"></i>'
  comm: <i class="icon-community" title="Community Contributed"></i>


extra_css:
  - css/access-nri.css
  - css/fontello.css