site_name: ACCESS-Hive

# Needed to generate the canonical_url for each pages that are 
# then used to create the sitemap for search engine indexing
site_url: https://access-hive.org.au
# Git repository
repo_url: https://github.com/ACCESS-Hive/access-hive.github.io
repo_name: ACCESS-Hive
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs
docs_dir: docs

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: custom-light
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: custom-dark
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

  features:
    - navigation.top
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.tracking       # The URL in the address bar is automatically updated with active anchor
    - content.action.edit
    - content.action.view
    - content.code.copy         # for displaying copy icon at top right in code snippets  
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow                # the sidebar is automatically scrolled to the active anchor

  logo: assets/ACCESS_icon_HIVE.png
  favicon: assets/ACCESS_icon_HIVE.png
  icon:
    edit: material/pencil
    view: material/eye
copyright: Copyright &copy; 2022 ACCESS-NRI

plugins:
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - search
  - macros
  - bibtex:
      bib_file: "references.bib"
  - events:
      events_dir: community_resources/events/events

# Extensions
markdown_extensions: 
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - footnotes
  - tables
  - pymdownx.keys
  - toc:
      title: On this page

# Navigation
nav:
  - Home: 
    - index.md
    - Contact: about/contact.md
    - Support: about/support.md
    - Contribute: 
      - Contribute: contribute/index.md
      - Edit on Github: contribute/edit-on-github.md
      - Edit Locally: contribute/edit-locally.md
      - Stand-alone Documentation: contribute/standalone-documentation.md
      - Change the Navigation: contribute/change-the-navigation.md
      - Reviewers: contribute/reviewers.md
    - Code of conduct: about/code_of_conduct.md
    - Policies: about/policies.md
    - License: about/License.md

  - Models: 
    - Models: models/index.md
    - Model Components: 
      - Overview: models/model_components/index.md
      - Atmosphere: models/model_components/atmosphere.md
      - Land: models/model_components/land.md
      - Ocean: models/model_components/ocean.md
      - Sea Ice: models/model_components/sea-ice.md
      - Aerosols and Atmospheric Chemistry: models/model_components/aerosols_atmospheric_chemistry.md
      - Biogeochemistry Land: models/model_components/bgc_land.md
      - Biogeochemistry Ocean: models/model_components/bgc_ocean.md
      - Coupler: models/model_components/coupler.md

    - Model Configurations: 
      - Overview: models/configurations/index.md
      - ACCESS-ESM: models/configurations/access-esm.md
      - ACCESS-CM: models/configurations/access-cm.md
      - ACCESS-AM: models/configurations/access-am.md
      - ACCESS-OM: models/configurations/access-om.md

  - Run a Model: 
    - models/run-a-model/index.md
    # If we add an additional subsection
    # - Getting Started: 
    #   - models/running-a-model/getting_started/index.md
    #   - Access to Gadi@NCI: models/running-a-model/getting_started/access_to_gadi_at_nci.md
    - Gadi Computing Access at NCI: models/run-a-model/getting_started/access_to_gadi_at_nci.md
    - Run ACCESS-ESM: models/run-a-model/run-access-esm.md
    - Run ACCESS-CM: models/run-a-model/run-access-cm.md
    - Run ACCESS-AM: models/run-a-model/run-access-am.md
    - Run ACCESS-OM: models/run-a-model/run-access-om.md

  - Model Evaluation:
    - model_evaluation/index.md
    - Getting Started: 
      - model_evaluation/model_evaluation_getting_started/index.md
      - Gadi Computing Access at NCI: model_evaluation/model_evaluation_getting_started/access_to_gadi_at_nci.md
      - Model Evaluation on Gadi: model_evaluation/model_evaluation_getting_started/model_evaluation_getting_started.md
      - Model Variables: model_evaluation/model_evaluation_getting_started/model_variables/index.md
        # - CMIP6: model_evaluation/model_evaluation_getting_started/model_variables/variables_cmip6.md
        # - ERA5: model_evaluation/model_evaluation_getting_started/model_variables/variables_era5.md
    - Data Catalogs:
      - Observational Data: model_evaluation/model_evaluation_observational_catalogs.md
      - Model Data:
        - model_evaluation/model_evaluation_model_catalogs/index.md
        - Search Model Catalog: model_evaluation/model_evaluation_model_catalogs/model_evaluation_search_models.md
        - Add your Model to the Catalog: model_evaluation/model_evaluation_model_catalogs/model_evaluation_add_models.md
        - Model Format Processing: model_evaluation/model_evaluation_data_processing.md
    - Evaluation Tools: 
      - model_evaluation/model_evaluation_on_gadi/index.md
      # - Frameworks on Gadi:
      - ILAMB: model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_ilamb.md
      - ESMValTool: model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_esmvaltool.md
      - COSIMA cookbook: model_evaluation/model_evaluation_on_gadi/model_evaluation_on_gadi_pangeo_cosima.md
      # - Live-Diagnostics on Gadi: model_evaluation/model_evaluation_live_diagnostics.md
      # - Evaluation Recipe Gallery: model_evaluation/model_evaluation_recipe_gallery.md

  - Community Resources:
    - community_resources/index.md
    - Working Groups: community_resources/community_working_groups.md
    - Glossaries: community_resources/glossaries/index.md
    - Model Evaluation Links:
      - Observational Catalogs: community_resources/community_observational_catalogs.md
      - Model Catalogs: community_resources/community_model_catalogs.md
      - Data Formatting: community_resources/community_data_processing.md
      - Evaluation Recipes: community_resources/community_med_recipes.md
    - Training: 
      - Training: community_resources/training/index.md
      - Git Version Control: community_resources/training/git-version-control.md
      - High Performance Computing (HPC): community_resources/training/hpc.md
      - ACCESS Training: community_resources/training/ACCESS_training.md
      - NCI Training: community_resources/training/nci-training.md
      - Additional Training: community_resources/training/additional_training.md
    - Events:
       - community_resources/events/index.md
       - Add Event: community_resources/events/add_event.md

  - Community Forum: https://forum.access-hive.org.au

# Footer
extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/ACCESS_NRI
      name: ACCESS-NRI on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/access-nri
      name: ACCESS-NRI on Linkedin
    - icon: fontawesome/brands/slack
      link: https://access-nri.slack.com/
      name: Join ACCESS-NRI Slack Channel
  analytics:
    provider: google
    property: G-2T6SQEH2CX

  # # Fontawesome icons
  # supported: '<a href="https://access-hive.org.au/about/support"><span class="icon-supported center-icons"><i class="fa fa-check" title="Supported by ACCESS-NRI"></i></span></a>'
  # recommended: '<a href="https://access-hive.org.au/about/support"><span class="icon-recommended center-icons"><i class="fa fa-star" title="Recommended by ACCESS-NRI"></i></span></a>'
  # community: '<a href="https://access-hive.org.au/about/support"><span class="heart center-icons"><i class="heart fa-regular fa-heart" title="Community Contributed"></i></span></a>'

extra_css:
  - css/fontello.css
  - "https://fonts.googleapis.com/icon?family=Material+Icons"   # Material Icons Reference - https://material.io/resources/icons/?style=baseline
  - css/fontawesome-free-6.4.0-web/css/fontawesome.css
  - css/fontawesome-free-6.4.0-web/css/solid.css
  - css/access-nri.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js     # For tablesort functionality 
  - js/terminal_animation.js
  - js/miscellaneous.js
