name: Check Markdown links

on: 
  push:
  schedule:
    # Run at 03:07 every Sunday
    - cron: "7 3 * * SUN"
  workflow_dispatch:

jobs:
  markdown-link-check:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/mlc_config.json'
        folder-path: 'docs'
        # Only check links in modified files to reduce false positives
        check-modified-files-only: 'yes'
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
  full-markdown-link-check:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: 'docs'
    