name: Check links

on: 
  pull_request: #Action fires anytime a PR is (re)opened or synchronized
    types:
      - opened
      - reopened
      - synchronize
  schedule: 
    # Run every Sunday at 03:07 (AEDT)
    # AEDT is UTC+10 --> Sunday at 03:07 AEDT is Saturday at 17:07 UTC
    - cron: "7 17 * * SAT"
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      if: ${{github.event_name == 'schedule'}}
      uses: actions/checkout@master
      with:
        ref: main

    - name: Checkout repo
      if: ${{github.event_name != 'schedule'}}
      uses: actions/checkout@master
    
    - name: Link checker
      uses: lycheeverse/lychee-action@v1.10.0
      with:
        fail: true
        args: --config .github/workflows/lychee-config.toml './docs/**/*.md' './docs/**/*.html'
