name: Deploy to GitHub Pages
on:
  push:
    branches: 
      - pr_test

jobs:
  pr-preview-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get date
        run: echo "DATE=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV

      - name: Set pr-preview URL
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          comment_tag: pr-preview
          pr_number: 613
          message: "\
            PR Preview

            :---:

            🛫 Deployment still ongoing.<br>
            Preview URL will be available at the end of the deployment.
            
            For more information, please check the [Actions](https://github.com/ACCESS-Hive/access-hive.github.io/actions) tab.

            ${{ env.DATE }}
            "

  build:
    runs-on: ubuntu-latest
    outputs:
      pr_nums: ${{ steps.build.outputs.pr_nums }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Build full website # main, development and PRs
        id: build
        shell: bash
        run: |
          retry() {
            command="$1"
            n_tries="$2"
            wait="$3"
            exit_msg="$4"
            eval "$command"
            until [ $? == 0 ]; do
              if [ $i -eq $((n_tries - 1)) ]; then
                echo "$exit_msg"
                exit 1
              else
                ((i++))
              fi
              sleep $wait
              eval "$command"
            done
          }
          
          git fetch --all
          command="pr_list=\$(curl -s https://api.github.com/repos/ACCESS-Hive/access-hive.github.io/pulls?state=opened | jq '.[] | select(.head.label!=\"ACCESS-Hive:development\")')"
          retry "$command" 5 1 "Failed to fetch opened PRs."
          pr_nums=($(jq '.number' <<< $pr_list))
          pr_sha=($(jq '.head.sha' <<< $pr_list))
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        shell: bash
        run: echo ${{ needs.build.outputs.pr_nums }}
  
  pr-preview:
    needs: [build,deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr_nums: ${{fromJson(needs.build.outputs.pr_nums)}}
    steps:
      - name: Get date
        run: echo "DATE=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV

      - name: Set pr-preview URL
        uses: thollander/actions-comment-pull-request@v2.4.3
        with:
          comment_tag: pr-preview
          pr_number: ${{ matrix.pr_nums }}
          message: "\
            PR Preview
              
            :---:

            🚀 Deployed preview to
            https://access-hive.org.au/pr-preview/pr-${{ matrix.pr_nums }}
            
            ${{ env.DATE }}
            "