name: Publish main website
on:
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: 
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: publish-website
  cancel-in-progress: false

env:
  TARGET_BRANCH: gh-pages

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADMIN_TOKEN }}
        
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run:  pip install -r requirements.txt
      - name: Build
        run: mkdocs build -f mkdocs.yml -d website
          
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website
          branch: ${{ env.TARGET_BRANCH }}
          clean-exclude: |
            pr-preview/
            development_website/