name: Remove PR preview

on:
  pull_request:
    types:
      - closed

concurrency: 
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  close-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      
      - name: Remove pr-preview
        shell: bash
        run: |
          folder=pr-preview/pr-${{ github.event.number }}
          if [ ! -d $folder ]
          then
            echo "Nothing to remove!"
            exit 0
          fi
          rm -rf $folder
          echo "Deleted $folder folder."
      
      - name: Commit to gh-pages
        shell: bash
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deleted 'pr-preview/pr-${{ github.event.number }}' folder."
          git push origin gh-pages
      
      # - name: Deploy to Github-pages

      - name: Get date
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M')" >> $GITHUB_ENV

      - name: Leave a comment after removal
        # if: env.deployment_status == 'success'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-preview
          number: ${{ github.event.number }}
          message: "\
            PR Preview

            :---:

            🛬 Preview removed because the pull request was closed.

            $DATE
            "