name: Full Check of markdown links

on:
  schedule:
    # Run at 03:07 every Sunday
    - cron: "7 3 * * Sun"
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/workflows/mlc_config.json'
        folder-path: 'docs'

