name: Test
on:
  # push:
  #   branches: 
  #     - test
  workflow_dispatch:
    
permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: Test # main, development and PRs
        shell: bash
        run: |
          ls -al
          echo "bubbi"
          ls -al ../